export const labels = {
    login: ' Login',
    email: ' E-mail',
    name: ' Nome',
    password: 'Senha',
    confirmPassword: 'Confirme a Senha',
    doLogin: 'Fazer Login',
    forgotPassword: 'Esqueci a Senha',
    register: 'Fazer Cadastro',
    facebookLogin: '──  Login com Facebook   ──',
    labelFacebook: ' Entrar com Facebook',
    understand: 'Ok, Entendi',
    facebookUrl: 'facebook.com',
    newSignUp: ' Novo Cadastro',
    signUp: 'Cadastrar',
    checkEmail: ' Verificação de E-mail',
    emailTo: 'Enviamos um e-mail de verificação para:',
    backHere: 'Após verificar, volte aqui para Continuar.',
    waitConfirmation: 'Aguardando Confirmação...',
    continue: 'Continuar ',
    unidentifiedEmail: 'Não recebeu o e-mail?',
    resendEmail: 'Reenviar e-mail',
    resendEmailIn: 'Reenviar e-mail em:',
    goBack: 'Voltar',
    goal: 'Metas',
    goalFormat: '(hhh:mm:ss)',
    equals: '=',
    forDay: ' horas / dia',
    startWeak: '* A semana começa no domingo.',
    saveGoal: 'Salvar Meta',
    skip: 'Pular',
    deleteGoal: 'Remover Meta',
    concluded: 'Concluída',
    started: 'Iniciada',
    toDo: 'A Fazer',
    tasks: 'Tarefas:',
    revisions: 'Revisões:',
    hello: 'Olá, ',
    subjects: 'Disciplinas',
    add: 'Adicionar',
    newSubject: 'Nova Disciplina',
    cancel: 'Cancelar',
    create: 'Criar',
    nameChangedSuccessfull: 'Nome alterado com sucesso!',
    editSubject: 'Editar Disciplina',
    changeName: 'Alterar Nome',
    late: '(Atrasada)',
    deleteContent: 'Deletar Conteudo',
    deleteFile: 'Deletar Arquivo',
    oneContent: '(1 Conteúdo)',
    moreContents: ' Conteúdos',
    withoutContent: '(Nenhum Conteúdo)',
    showing: 'Mostrando: ',
    close: 'Fechar',
    save: 'Salvar',
    delete: 'Excluir',
    files: 'Arquivos',
    type: 'Tipo: ',
    review: 'Revisão',
    questions: 'Questões',
    tasks: 'Tarefa',
    start: 'Iniciar',
    pause: 'Pausar',
    reset: 'Zerar',
    timeFormat: '(hh:mm:ss)',
    concludedIn: 'Tarefa Concluida em:',
    reviewIn: 'Revisar em:',
    saveProgress: 'Salvar Progresso',
    finishTask: 'Finalizar Tarefa',
    annotations: 'Não há anotações.',
    end: 'Finalizar',
    annotationsAndAnexos: 'Anotações e anexo',
    defaultTime: '00:00:00',
    goalType: 'Tipo de meta:',
    goalLabel: 'Meta:',
    timeDone: 'Tempo Realizado:',
    timeLeft: 'Tempo Restante:',
    daysLeft: 'Dias Restante:',
    changeOrCancelGoal: 'Alterar ou cancelar meta',
    lastSevenDays: `Últimos${'\n'}7 Dias`,
    lastFifteenDays: `Últimos${'\n'}15 Dias`,
    customPeriod: `Custom.{'\n'}período`,
    
}

